import pugqrIcon from './pugqr-icon.png'
import mailIcon from './mailIcon.svg'
import userIcon from './mdi--user-outline.svg'
import passwordIcon from './passwordIcon.svg'
import checkboxIcon from './checkboxIcon.svg'
import humanpetIcon from './humanwithpet.png'
import petqrIcon from './petqr-icon.svg'
import backgroundTheme from './background.png'
import stampImage from './fingerprint.png'
import userSvg from './userSvg.svg'
import backgroundCathuman from './background-cathuman.png'
import catSleepingIcon from './catsleepingIcon.png'
import backgroundPet from './backgroundPet.png'
import animalPortals from './animalsPortal.png'
import secureIcon from './secureIcon.svg'
import communityIcon from './communityIcon.svg'
export { pugqrIcon, mailIcon, userIcon, passwordIcon, checkboxIcon, humanpetIcon, petqrIcon, backgroundTheme, stampImage, userSvg, backgroundCathuman, catSleepingIcon, backgroundPet, animalPortals, secureIcon, communityIcon }
  